version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot-image:dev
    command: >
      sh -c "alembic upgrade head &&
             python main.py"
    volumes:
      - .:/bot
    env_file:
      - ./.env
    depends_on:
      - redis

  admin_panel:
    image: bot-image:dev
    volumes:
      - .:/bot
    expose:
      - 5000
    depends_on:
      - bot
    env_file:
      - ./.env
    command: python admin_panel.py

  redis:
    image: redis:6.0.6-alpine
    expose:
      - 6379

  db:
    image: postgres:12.0-alpine
    volumes:
      - bot_db:/var/lib/postgresql/data/
    expose:
      - 5432

  nginx:
    build:
      context: ./nginx
      dockerfile: Dev.Dockerfile
    image: nginx:dev
    ports:
      - 80:80
      - target: 443
        published: 443
        mode: host
    depends_on:
      - bot
      - admin_panel


volumes:
    bot_db: