"""User language

Revision ID: c016775840c3
Revises: c569ec15ec51
Create Date: 2023-04-12 15:48:54.925327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = 'c016775840c3'
down_revision = 'c569ec15ec51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    companytype_enum = postgresql.ENUM('ua', 'en', name='language', create_type=False)
    companytype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('language', sa.Enum('ua', 'en', name='language'), nullable=True))
    op.drop_constraint('users_role_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_fkey', 'users', 'roles', ['role'], ['id'])
    op.drop_column('users', 'language')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
